### ISSUE TITLE
GetLanguageByContent returns an empty string

### ISSUE THREAD

**Issue by kuba--** [go-enry/go-enry#145] opened 2022-11-26 21:27 UTC
Following code returns an empty string:
```go
language, _ := enry.GetLanguageByContent("foo.cpp", "int main() { return 0; }")
```
Expected: `language == "C++"`

**Comment by bzz** [comment] 2022-11-29 21:46
Well, after looking into it - this is not a bug 😁 but rather an unfortunate consequence of the way we expose as public APIs what, in reality, are an internal linguist matching strategies 🤷 .

As [GetLanguagesByContent](https://github.com/go-enry/go-enry#by-file) documented - it uses content-based heuristics to _disambiguate_ between languages that have colliding file extension.

I.e. ".cpp" is unambiguous - it's not even present in [heuristics.yml](https://github.com/github/linguist/blob/master/lib/linguist/heuristics.yml) which is EXACTLY what `content.go` is and what backs `GetLanguagesByContent`.  Indeed, then there is "no match" and that is [enry. OtherLanguage](https://pkg.go.dev/github.com/go-enry/go-enry/v2#pkg-constants)  😵‍💫 

My bet is that, as an API client, from the method name one expects it to behave more like something from https://github.com/go-enry/go-enry#by-text

**Comment by bzz** [comment] 2022-12-12 19:51
Because closing issues always feels productive and as there is no further discussion - I'll close this for now.
But please, don't hesitate to re-open it if there are some further questions/remarks/suggestions! 
I hope additional unit-tests help to clarify expectations a bit.

**Closed by bzz** 2022-12-12 19:51 UTC
Labels: question
